### PR TITLE
Completed css-three-column-layout exercise. - Tiffany Brown

### PR DESCRIPTION
**Pull request by tiffanydbrown**
Screenshot 2023-11-02 at 12 19 04 PM

### CODE REVIEW

**Review by shawnkost — CHANGES_REQUESTED** [review]
Doesn't quite look like the example image Tiffany! This should look so close that I should have a hard time seeing any differences

**Review by shawnkost — CHANGES_REQUESTED** [review]
Please include an updated screenshot so I can verify the changes worked

**Comment by tiffanydbrown** [comment]
Screenshot 2023-11-02 at 7 23 32 PM

**Review by shawnkost — CHANGES_REQUESTED** [review]
It looks like everything is aligned to the left, rather than being in the center. You need to do the following

1. Give `text-align: center` to your heading
2. On your `.column`s, you should make them flex containers and change the `flex-direction` to `column`. Then you can use `justify-content` & `align-items` to center the columns

**Comment by tiffanydbrown** [comment]
Screenshot 2023-11-03 at 9 04 13 AM

**Review by shawnkost — APPROVED** [review]
👍🏻

**Pull request merged**
